name: Build Dev

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build Dev Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Unit tests
        run: |
          npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          aws-region: eu-central-1

      - name: Copy stack cfn parameters from S3 bucket and set as cdk context
        run: |
          aws s3 cp s3://akurat-artifacts/distribution/dev/config.json cdk.context.json

      - name: AWS CDK diff
        uses: youyo/aws-cdk-github-actions@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cdk_subcommand: 'diff'
          cdk_stack: 'dev-AkuratStack'
          actions_comment: true